### ISSUE TITLE
Working with Arrays in JavaScript Quiz

### ISSUE THREAD

**Issue by k8obrien** [learn-co-curriculum/phase-1-quiz-working-with-arrays-in-javascript-quiz#1]
### Canvas Link

https://learning.flatironschool.com/courses/4330/quizzes/20520

### Concern

this test would have been a 100% if answers 1, 3 and 7 had correct answer variations. Every method answer that was entered into the quiz was followed by a () and only 5, 8 and 10 included correct answer variations.

### Suggested Changes

please add answer variations to answers 1, 3 and 5.

**Comment by ihollander** [comment]
Hi @k8obrien - thanks for your feedback! For the questions you mentioned, the prompt is to fill in the blank in the code, for example:

```js
let artists = [
  "Smash Mouth",
  "Janelle Monae",
  "SZA",
  "Thunder Cat",
  "Frank Ocean",
  "Solange",
];

artists._________(function (artist) {
  return artist.startsWith("S");
});
```

Here, the correct answer to fill in the blank is `filter`. If `filter()` was entered in the blank in the code above, it wouldn't be valid:

```js
let artists = [
  "Smash Mouth",
  "Janelle Monae",
  "SZA",
  "Thunder Cat",
  "Frank Ocean",
  "Solange",
];

artists.filter()(function (artist) {
  return artist.startsWith("S");
});
```

Since `filter` needs to be called with a callback function as its argument, the code above wouldn't work.

For the other questions in this quiz that don't provide an explicit example with code, we provided multiple possible correct answers (with parentheses and without) to try and account for different solutions, but for the code examples, there's only one correct answer to fill in the blank.

It sounds like you have the right understanding of what methods to use with arrays though, so you're on the right track!
